"""The project documentation (`documentation.md`): the structure of the Architecture Master
Playbook, cut to what a team needs to understand the analyzed system — no diagrams.

Sections come from the graph (deterministic, with evidence in the other documents) except
problem/goals, principles, assumptions and glossary, which the code cannot state: those come
from the inferred project context, marked as inferred, or show the questions the team has to
answer when nothing was inferred. Written in the chosen language, like the report and the AI
texts.
"""

from collections import Counter

from exodus.application.ports import Document, Language
from exodus.domain.documentation import OpenQuestion, Question, drivers, open_questions
from exodus.domain.graph import ArchitectureGraph
from exodus.domain.migration import plan_migration
from exodus.domain.model import Node, NodeKind, RelKind
from exodus.domain.risks import Severity, assess_risks
from exodus.domain.views import entry_points
from exodus.infrastructure.rendering.common import localize, pick

_NOT_INFERRED = {
    Language.PT_BR: "*Não inferido (IA indisponível).* Perguntas para o time responder:",
    Language.EN: "*Not inferred (AI unavailable).* Questions for the team to answer:",
}
_QUESTIONS = {
    Language.PT_BR: {
        "problem": [
            "Por que este sistema existe? Qual problema de negócio ele resolve?",
            "Quem depende dele no dia a dia?",
            "Quais objetivos de negócio ele atende (e como medir)?",
        ],
        "principles": [
            "Que padrões de arquitetura o sistema segue (camadas, eventos, CQRS…)?",
            "Que regras o time sempre respeitou ao evoluí-lo?",
        ],
        "assumptions": [
            "O que se assume como verdadeiro sem confirmação (volumes, horários, integrações)?",
        ],
        "glossary": ["Quais termos de negócio e siglas aparecem no código e o que significam?"],
    },
    Language.EN: {
        "problem": [
            "Why does this system exist? What business problem does it solve?",
            "Who depends on it day to day?",
            "Which business goals does it serve (and how are they measured)?",
        ],
        "principles": [
            "Which architecture patterns does the system follow (layers, events, CQRS…)?",
            "Which rules has the team always kept when evolving it?",
        ],
        "assumptions": [
            "What is taken as true without confirmation (volumes, schedules, integrations)?",
        ],
        "glossary": ["Which business terms and acronyms appear in the code and what do they mean?"],
    },
}
_OBJECTS = {
    Language.PT_BR: {"table": "Tabela", "collection": "Coleção", "procedure": "Procedure"},
    Language.EN: {"table": "Table", "collection": "Collection", "procedure": "Procedure"},
}
MAX_LISTED = 8  # names shown before "+N"


class DocumentationRenderer:
    def __init__(self, language: Language = Language.PT_BR) -> None:
        self.language = language

    def _t(self, pt_br: str, en: str) -> str:
        return pick(self.language, pt_br, en)

    def render(self, graph: ArchitectureGraph) -> list[Document]:
        systems = graph.nodes(NodeKind.SYSTEM)
        if not systems:
            return []
        names = ", ".join(s.name for s in systems)
        lines = [
            self._t(f"# {names} — documentação do projeto", f"# {names} — project documentation"),
            "",
            self._t(
                "> Gerado pelo Exodus a partir do código-fonte e da configuração. O que foi "
                "inferido por IA está marcado como *inferido*; o resto vem do código, com "
                "evidência nos outros documentos (`inventory.md`, `risks.md`, `migration.md`). "
                "Complete e ajuste: este é um documento vivo.",
                "> Generated by Exodus from the source code and configuration. What was inferred "
                "by AI is marked as *inferred*; the rest comes from the code, with evidence in the "
                "other documents (`inventory.md`, `risks.md`, `migration.md`). Complete and "
                "adjust it: this is a living document.",
            ),
            "",
        ]
        t = self._t
        sections = [
            (t("0. Visão geral", "0. Overview"), self._overview),
            (t("1. Problema e objetivos", "1. Problem and goals"), self._problem),
            (t("2. Escopo e contexto", "2. Scope and context"), self._scope),
            (t("3. O que o sistema faz", "3. What the system does"), self._capabilities),
            (t("4. Restrições, premissas e dependências",
               "4. Constraints, assumptions and dependencies"), self._constraints),
            (t("5. O que pesa na migração (drivers)", "5. What drives the migration"),
             self._drivers),
            (t("6. Princípios e padrões", "6. Principles and patterns"), self._principles),
            (t("7. Decisões de migração", "7. Migration decisions"), self._decisions),
            (t("8. Como funciona", "8. How it works"), self._how_it_works),
            (t("9. Implantação", "9. Deployment"), self._deployment),
            (t("10. Testes", "10. Tests"), self._tests),
            (t("11. Riscos", "11. Risks"), self._risks),
            (t("12. Evolução: ondas de migração", "12. Evolution: migration waves"),
             self._evolution),
            (t("13. Questões em aberto", "13. Open questions"), self._open),
            (t("14. Glossário", "14. Glossary"), self._glossary),
        ]  # fmt: skip
        for title, section in sections:
            lines += [f"## {title}", "", *section(graph, systems), ""]
        return [Document(name="documentation.md", content="\n".join(lines))]

    def _overview(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        containers = graph.nodes(NodeKind.CONTAINER)
        runtimes = Counter(
            " / ".join(
                v for v in (c.attributes.get("language"), c.attributes.get("framework")) if v
            )
            or self._t("desconhecido", "unknown")
            for c in containers
        )
        stores, queues = len(graph.nodes(NodeKind.DATA_STORE)), len(graph.nodes(NodeKind.QUEUE))
        externals = len(graph.nodes(NodeKind.EXTERNAL_SYSTEM))
        size = self._t(
            f"{len(containers)} container(s), {stores} banco(s), {queues} fila(s), "
            f"{externals} sistema(s) externo(s)",
            f"{len(containers)} container(s), {stores} database(s), {queues} queue(s), "
            f"{externals} external system(s)",
        )
        lines = [
            "| | |",
            "|---|---|",
            f"| **{self._t('Sistemas', 'Systems')}** | {', '.join(s.name for s in systems)} |",
            self._t(
                "| **Tipo** | Legado (brownfield) a migrar para a AWS |",
                "| **Type** | Legacy (brownfield) to migrate to AWS |",
            ),
            f"| **Stack** | {_counts(runtimes)} |",
            f"| **{self._t('Tamanho', 'Size')}** | {size} |",
            "",
        ]
        for s in systems:
            if s.description:
                lines.append(
                    f"**{s.name} {self._t('em uma frase', 'in one sentence')}** "
                    f"({self._inferred(s.description.confidence)}): {s.description.text}"
                )
        return lines

    def _problem(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        lines: list[str] = []
        for s in systems:
            context = graph.project_context(s.id)
            lines += _heading(s, systems)
            if context is None or not (context.problem or context.goals):
                lines += self._ask("problem")
                continue
            lines.append(f"{self._inferred(context.confidence)}: {context.problem}")
            if context.goals:
                goals = self._t("**Objetivos**", "**Goals**")
                lines += ["", goals, "", *[f"- {g}" for g in context.goals]]
            lines.append("")
        return lines

    def _scope(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        lines = [self._t("**Sistemas analisados**", "**Analyzed systems**"), ""]
        for s in systems:
            count = len(graph.children(s.id, NodeKind.CONTAINER))
            lines.append(f"- {s.name}: {count} container(s)")
        externals = graph.nodes(NodeKind.EXTERNAL_SYSTEM)
        if externals:
            lines += ["", self._t("**Sistemas externos com que conversa**",
                                  "**External systems it talks to**"), ""]  # fmt: skip
            called_by = self._t("chamado por", "called by")
            lines += [
                f"- {e.name} ({called_by} {', '.join(_users(graph, e.id))})" for e in externals
            ]
        kinds = Counter(e.kind for c in graph.nodes(NodeKind.CONTAINER) for e in entry_points(c))
        entries = _counts(kinds) or self._t(
            "nenhum ponto de entrada detectado", "no entry point detected"
        )
        lines += ["", f"**{self._t('Entradas', 'Inputs')}:** {entries}"]
        messages = len(graph.relationships(RelKind.PUBLISHES))
        stores, queues = len(graph.nodes(NodeKind.DATA_STORE)), len(graph.nodes(NodeKind.QUEUE))
        outputs = self._t(
            f"{stores} banco(s), {queues} fila(s), {messages} fluxo(s) de eventos, "
            f"{len(externals)} sistema(s) externo(s)",
            f"{stores} database(s), {queues} queue(s), {messages} event flow(s), "
            f"{len(externals)} external system(s)",
        )
        lines.append(
            f"**{self._t('Saídas e dependências', 'Outputs and dependencies')}:** {outputs}"
        )
        return lines

    def _capabilities(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        lines: list[str] = []
        for c in graph.nodes(NodeKind.CONTAINER):
            entries = entry_points(c)
            what = f" — {c.description.text} ({self._mark()})" if c.description else ""
            lines.append(f"- **{c.name}**{what}")
            if entries:
                shown = [f"{e.kind} {e.name}" for e in entries]
                label = self._t("Pontos de entrada", "Entry points")
                lines.append(f"  - {label} ({len(entries)}): {_listed(shown)}")
        use_cases = graph.use_cases()
        if use_cases:
            lines += ["", self._t(
                "**Casos de uso principais** (*inferidos*; passo a passo em `use-cases.md`)",
                "**Main use cases** (*inferred*; steps in `use-cases.md`)",
            ), ""]  # fmt: skip
            lines += [f"- {u.title} ({u.trigger_kind} `{u.trigger}`)" for u in use_cases]
        return lines

    def _constraints(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        containers = graph.nodes(NodeKind.CONTAINER)
        runtimes = Counter(
            c.attributes["framework"] for c in containers if "framework" in c.attributes
        )
        technologies = Counter(
            k.removeprefix("technology:") for c in containers for k in c.attributes
            if k.startswith("technology:")
        )  # fmt: skip
        lines = [self._t("**Restrições (do código)**", "**Constraints (from the code)**"), ""]
        lines.append(f"- Runtimes: {_counts(runtimes) or self._t('não identificados', 'unknown')}")
        if technologies:
            label = self._t("Tecnologias legadas", "Legacy technologies")
            lines.append(f"- {label}: {_counts(technologies)}")
        lines += ["", self._t("**Premissas**", "**Assumptions**"), ""]
        for s in systems:
            context = graph.project_context(s.id)
            lines += _heading(s, systems)
            if context is None or not context.assumptions:
                lines += self._ask("assumptions")
            else:
                lines += [f"- {a} ({self._mark()})" for a in context.assumptions] + [""]
        t = self._t
        lines += [t("**Dependências**", "**Dependencies**"), ""]
        for kind, label in [(NodeKind.DATA_STORE, t("Bancos", "Databases")),
                            (NodeKind.QUEUE, t("Filas", "Queues")),
                            (NodeKind.EXTERNAL_SYSTEM, t("Sistemas externos", "External systems")),
                            (NodeKind.PLATFORM, t("Plataforma", "Platform"))]:  # fmt: skip
            nodes = graph.nodes(kind)
            if nodes:
                named = [f"{n.name} ({n.technology})" if n.technology else n.name for n in nodes]
                lines.append(f"- {label}: {_listed(named)}")
        return lines

    def _drivers(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        found = [d for s in systems for d in drivers(graph, s)]
        if not found:
            return [
                self._t(
                    "Nenhum risco alto: nada força uma estratégia específica.",
                    "No high risk: nothing forces a specific strategy.",
                )
            ]
        return [f"- **{d.title}** ({d.detail}): {_listed(list(d.where))}" for d in found]

    def _principles(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        lines: list[str] = []
        for s in systems:
            context = graph.project_context(s.id)
            lines += _heading(s, systems)
            if context is None or not context.principles:
                lines += self._ask("principles")
                continue
            basis = self._t("base", "basis")
            lines += [
                f"- {p.text} ({self._mark()}; {basis}: {p.basis})" for p in context.principles
            ]
            lines.append("")
        return lines

    def _decisions(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        plan = plan_migration(graph)
        t = self._t
        same = t("= caminho rápido", "= fast path")
        paths: dict[tuple[str, str], list[str]] = {}
        for c in plan.containers:
            fast = f"{c.fast.strategy} → {c.fast.target}"
            modern = f"{c.modern.strategy} → {c.modern.target}" if c.modern else same
            paths.setdefault((fast, modern), []).append(graph.node(c.container_id).name)
        lines = [t("Por regra (sem IA; detalhes e 7R em `migration.md`):",
                   "By rule (no AI; details and 7R in `migration.md`):"), ""]  # fmt: skip
        lines += [
            f"- {_listed(sorted(names))}: {t('rápido', 'fast')} **{fast}**; "
            f"{t('moderno', 'modern')} **{modern}**"
            for (fast, modern), names in paths.items()
        ]
        infra = [
            f"{graph.node(i.node_id).name} → {i.fast}"
            for i in plan.infrastructure
            if graph.node(i.node_id).kind is not NodeKind.PLATFORM
        ]
        if infra:
            lines.append(f"- {t('Dados e filas', 'Data and queues')}: {_listed(infra)}")
        refactor = graph.refactor
        if refactor is not None and refactor.choices:
            chosen: dict[str, list[str]] = {}
            for choice in refactor.choices:
                chosen.setdefault(choice.service, []).append(graph.node(choice.node_id).name)
            proposed = t(
                "Refactor proposto pela IA (*inferido*; ADRs em `to-be/adr/`):",
                "Refactor proposed by the AI (*inferred*; ADRs in `to-be/adr/`):",
            )
            lines += ["", proposed, ""]
            lines += [
                f"- {service}: {_listed(sorted(names))}"
                for service, names in sorted(chosen.items(), key=lambda item: -len(item[1]))
            ]
            lines += [
                t(f"- Fundir {graph.node(m.source_id).name} em {graph.node(m.into_id).name}: ",
                  f"- Merge {graph.node(m.source_id).name} into {graph.node(m.into_id).name}: ")
                + m.justification
                for m in refactor.merges
            ]  # fmt: skip
        return lines

    def _how_it_works(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        t = self._t
        lines: list[str] = []
        for c in graph.nodes(NodeKind.CONTAINER):
            parts = [f"**{c.name}**"]
            if c.description:
                parts.append(f"{c.description.text} ({self._mark()}).")
            outgoing = _targets(graph, c.id)
            labels = [(RelKind.CALLS, t("Chama", "Calls")),
                      (RelKind.PUBLISHES, t("Publica para", "Publishes to"))]  # fmt: skip
            for kind, label in labels:
                names = [n for k, n in outgoing if k is kind]
                if names:
                    parts.append(f"{label}: {_listed(names)}.")
            data = [n for k, n in outgoing if k is RelKind.DEPENDS_ON]
            if data:
                parts.append(f"{t('Usa', 'Uses')}: {_listed(data)}.")
            callers = _users(graph, c.id, RelKind.CALLS)
            if callers:
                parts.append(f"{t('Recebe chamadas de', 'Called by')}: {_listed(callers)}.")
            lines.append("- " + " ".join(parts))
        return lines

    def _deployment(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        lines: list[str] = []
        for s in systems:
            compose = [(k.removeprefix("compose:"), v) for k, v in s.attributes.items()
                       if k.startswith("compose:")]  # fmt: skip
            if compose:
                lines.append(f"- docker-compose {self._t('de', 'of')} {s.name}: "
                             f"{_listed([f'{n} ({image})' for n, image in compose])}")  # fmt: skip
        images: dict[str, list[str]] = {}  # runtime image -> containers: the big picture
        for c in graph.nodes(NodeKind.CONTAINER):
            if image := c.attributes.get("runtime-image"):
                images.setdefault(image, []).append(c.name)
        label = self._t("Imagem", "Image")
        lines += [f"- {label} {image}: {_listed(names)}" for image, names in images.items()]
        return lines or [
            self._t(
                "Nenhum Dockerfile nem docker-compose encontrado.",
                "No Dockerfile or docker-compose found.",
            )
        ]

    def _tests(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        containers = graph.nodes(NodeKind.CONTAINER)
        tested = [(c.name, _prefixed(c, "test-project:")) for c in containers]
        lines = [f"- {name}: {_listed(projects)}" for name, projects in tested if projects]
        if not lines:
            return [self._t("Nenhum projeto de teste encontrado.", "No test project found.")]
        untested = [name for name, projects in tested if not projects]
        if untested:
            label = self._t("Sem testes encontrados", "No tests found")
            lines.append(f"- {label}: {_listed(untested)}")
        return lines

    def _risks(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        severities = Counter(r.severity for r in assess_risks(graph))
        high, medium = severities[Severity.HIGH], severities[Severity.MEDIUM]
        low = severities[Severity.LOW]
        return [
            self._t(
                f"{high} alto(s), {medium} médio(s), {low} baixo(s). Os altos estão na seção 5; "
                "todos, com evidência, em `risks.md`.",
                f"{high} high, {medium} medium, {low} low. The high ones are in section 5; all "
                "of them, with evidence, in `risks.md`.",
            )
        ]

    def _evolution(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        plan = plan_migration(graph)
        wave_label = self._t("Onda", "Wave")
        lines: list[str] = []
        if plan.foundation:
            lines.append(
                self._t("- **Onda 0 — fundação:** ", "- **Wave 0 — foundation:** ")
                + _listed([graph.node(p).name for p in plan.foundation])
            )
        for wave in plan.waves:
            groups = []
            for g in wave.groups:
                names = ", ".join(graph.node(i).name for i in g.container_ids)
                reasons = "; ".join(localize(r, self.language) for r in g.reasons)
                groups.append(f"{names}" + (f" ({reasons})" if reasons else ""))
            lines.append(f"- **{wave_label} {wave.number}:** " + " | ".join(groups))
        return lines or [self._t("Nada a migrar.", "Nothing to migrate.")]

    def _open(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        questions = [self._question(q) for s in systems for q in open_questions(graph, s)]
        return [f"- {q}" for q in questions] or [
            self._t(
                "Nenhuma questão em aberto na extração.", "No open question from the extraction."
            )
        ]

    def _question(self, q: OpenQuestion) -> str:
        t, name, detail = self._t, q.subject, q.detail
        match q.kind:
            case Question.UNRESOLVED_DATASOURCE:
                return t(f"Fonte de dados não reconhecida em {name}: {detail}",
                         f"Unrecognized data source in {name}: {detail}")  # fmt: skip
            case Question.UNDETERMINED_DATABASE:
                kind, _, obj = detail.partition(":")
                label = _OBJECTS[self.language].get(kind, kind)
                return t(f"{label} {obj} em {name}: base de dados não determinada",
                         f"{label} {obj} in {name}: database not determined")  # fmt: skip
            case Question.NO_AWS_TARGET:
                return t(f"Sem regra de destino AWS para {name} ({detail}): avaliar",
                         f"No AWS target rule for {name} ({detail}): evaluate")  # fmt: skip
            case Question.NO_MIGRATION_RULE:
                return t(f"Sem regra de migração para {name} ({detail}): avaliar",
                         f"No migration rule for {name} ({detail}): evaluate")  # fmt: skip
            case Question.RETIRE_CANDIDATE:
                return t(
                    f"{name}: candidato a Retire (nenhum ponto de entrada nem chamada recebida); "
                    "confirmar uso",
                    f"{name}: Retire candidate (no entry point and no incoming call); "
                    "confirm usage",
                )

    def _glossary(self, graph: ArchitectureGraph, systems: list[Node]) -> list[str]:
        terms = [
            (t.term, t.meaning)
            for s in systems
            if (context := graph.project_context(s.id)) is not None
            for t in context.glossary
        ]
        if not terms:
            return self._ask("glossary")
        lines = [
            self._t(
                "*Inferido* a partir dos nomes do código.", "*Inferred* from the code's names."
            ),
            "",
            self._t("| Termo | Significado |", "| Term | Meaning |"),
            "|---|---|",
        ]
        return lines + [f"| {term} | {meaning} |" for term, meaning in sorted(set(terms))]

    def _ask(self, section: str) -> list[str]:
        questions = _QUESTIONS[self.language][section]
        return [_NOT_INFERRED[self.language], "", *[f"- {q}" for q in questions], ""]

    def _mark(self) -> str:
        return self._t("*inferido*", "*inferred*")

    def _inferred(self, confidence: float) -> str:
        return f"{self._mark()} ({confidence:.0%})"


def _prefixed(node: Node, prefix: str) -> list[str]:
    return [key.removeprefix(prefix) for key in node.attributes if key.startswith(prefix)]


def _heading(system: Node, systems: list[Node]) -> list[str]:
    return [f"**{system.name}**", ""] if len(systems) > 1 else []


def _counts(counter: Counter[str]) -> str:
    return ", ".join(f"{name} ({count})" for name, count in counter.most_common())


def _listed(names: list[str]) -> str:
    shown = ", ".join(names[:MAX_LISTED])
    hidden = len(names) - MAX_LISTED
    return f"{shown} (+{hidden})" if hidden > 0 else shown


def _users(graph: ArchitectureGraph, node_id: str, kind: RelKind | None = None) -> list[str]:
    names = {
        container.name
        for r in graph.relationships(kind)
        if r.target_id == node_id
        and (container := graph.ancestor(r.source_id, NodeKind.CONTAINER)) is not None
        and container.id != node_id
    }
    return sorted(names)


def _targets(graph: ArchitectureGraph, container_id: str) -> list[tuple[RelKind, str]]:
    found = {
        (r.kind, graph.node(r.target_id).name)
        for r in graph.relationships()
        if r.source_id == container_id and graph.node(r.target_id).kind is not NodeKind.PLATFORM
    }
    return sorted(found, key=lambda item: item[1])
