"""Render the optional inferred system overview."""

from exodus.application.ports import Document
from exodus.domain.graph import ArchitectureGraph
from exodus.domain.model import NodeKind


class OverviewRenderer:
    def render(self, graph: ArchitectureGraph) -> list[Document]:
        lines = [
            "# Exodus — Overview",
            "",
            "> Descriptions marked *inferred* were generated by AI from extracted evidence.",
            "",
        ]
        for system in graph.nodes(NodeKind.SYSTEM):
            lines += [f"## {system.name}", ""]
            if system.description:
                lines += [_description(system.description.text, system.description.confidence), ""]
            for container in graph.children(system.id, NodeKind.CONTAINER):
                if container.description:
                    description = _description(
                        container.description.text, container.description.confidence
                    )
                    lines += [f"- **{container.name}:** {description}"]
            lines.append("")
        return [Document(name="overview.md", content="\n".join(lines))]


def _description(text: str, confidence: float) -> str:
    return f"*inferred* ({confidence:.0%}): {text}"
