"""The HTML report: one self-contained page for whoever decides the migration.

Summary first, then AS-IS, risks, migration and TO-BE, and the details (inventory, use cases,
components, ADRs) folded at the end. Numbers come from the domain (risks, migration plan,
views), diagrams are inline SVG from the same layout as the draw.io files, and the details
reuse the Markdown documents. Fixed texts are in the chosen language, like what the AI writes.
"""

import html
from collections import Counter
from collections.abc import Iterable

from exodus.application.ports import Document, Language
from exodus.domain.graph import ArchitectureGraph
from exodus.domain.migration import MigrationPlan, Path, plan_migration
from exodus.domain.model import NodeKind
from exodus.domain.refactor import Catalog, refactor_view
from exodus.domain.risks import Risk, Severity, assess_risks
from exodus.domain.to_be import replatform_views
from exodus.domain.views import component_views, container_views, system_context
from exodus.infrastructure.rendering.adr import AdrRenderer
from exodus.infrastructure.rendering.common import evidence_summary, localize, pick
from exodus.infrastructure.rendering.inventory import InventoryRenderer
from exodus.infrastructure.rendering.markdown_html import inline, to_html
from exodus.infrastructure.rendering.svg import AwsSvg, C4Svg, svg
from exodus.infrastructure.rendering.use_cases import UseCasesRenderer

_CSS = """
:root { --bg: #ffffff; --fg: #1f2328; --muted: #57606a; --line: #d0d7de; --card: #f6f8fa;
        --high: #cf222e; --accent: #0969da; }
@media (prefers-color-scheme: dark) {
  :root { --bg: #0d1117; --fg: #e6edf3; --muted: #9198a1; --line: #30363d; --card: #161b22;
          --high: #ff7b72; --accent: #4493f8; } }
* { box-sizing: border-box; }
body { margin: 0 auto; max-width: 1200px; padding: 24px 16px 64px; background: var(--bg);
       color: var(--fg); font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
h1 { font-size: 28px; margin-bottom: 4px; } h2 { border-bottom: 1px solid var(--line);
     padding-bottom: 6px; margin-top: 40px; } .muted { color: var(--muted); fill: var(--muted); }
a { color: var(--accent); } code { background: var(--card); padding: 1px 4px; border-radius: 4px;
    font-size: 13px; overflow-wrap: anywhere; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 14px; }
th, td { border: 1px solid var(--line); padding: 6px 8px; text-align: left; vertical-align: top; }
th { background: var(--card); }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; }
.card { background: var(--card); border: 1px solid var(--line); border-radius: 8px; padding: 12px; }
.card b { display: block; font-size: 26px; } .high { color: var(--high); font-weight: bold; }
figure { margin: 16px 0; background: #ffffff; border: 1px solid var(--line); border-radius: 8px;
         padding: 12px; overflow-x: auto; }
figure svg { display: block; width: 100%; height: auto; cursor: zoom-in;
              font-family: system-ui, sans-serif; }
figure.zoom svg { width: auto; max-width: none; cursor: zoom-out; }
figcaption { color: #57606a; font-size: 13px; margin-bottom: 6px; }
details { border: 1px solid var(--line); border-radius: 8px; padding: 8px 12px; margin: 12px 0; }
summary { cursor: pointer; font-weight: bold; }
@media print { details { display: block; } figure { break-inside: avoid; } }
"""


class ReportRenderer:
    def __init__(self, catalog: Catalog, language: Language = Language.PT_BR) -> None:
        self.catalog = catalog
        self.language = language

    def _t(self, pt_br: str, en: str) -> str:
        return pick(self.language, pt_br, en)

    def _localize(self, text: str) -> str:
        return localize(text, self.language)

    def render(self, graph: ArchitectureGraph) -> list[Document]:
        if not graph.nodes(NodeKind.SYSTEM):
            return []
        risks = assess_risks(graph)
        plan = plan_migration(graph)
        systems = ", ".join(s.name for s in graph.nodes(NodeKind.SYSTEM))
        body = [
            self._t(
                f"<h1>Relatório de migração para AWS — {_e(systems)}</h1>",
                f"<h1>AWS migration report — {_e(systems)}</h1>",
            ),
            self._t(
                '<p class="muted">Gerado pelo Exodus a partir do código-fonte e da configuração. '
                "Cada elemento e seta aponta para o arquivo e a linha de onde veio (passe o "
                "mouse); o que foi inferido por IA está marcado como <em>inferido</em>. "
                "Documentação do projeto para o time (propósito, escopo, decisões, questões em "
                "aberto) em <code>documentation.md</code>.</p>",
                '<p class="muted">Generated by Exodus from the source code and configuration. '
                "Each element and arrow points to the file and line it came from (hover over "
                "it); what was inferred by AI is marked as <em>inferred</em>. Project "
                "documentation for the team (purpose, scope, decisions, open questions) in "
                "<code>documentation.md</code>.</p>",
            ),
            *self._summary(graph, risks, plan),
            *self._as_is(graph),
            *self._risks(graph, risks),
            *self._migration(graph, plan),
            *self._to_be(graph),
            *self._details(graph),
        ]
        page = (
            f'<!doctype html>\n<html lang="{self._t("pt-BR", "en")}">\n<head>\n'
            '<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
            '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; '
            "style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'\">\n"
            f"<title>Exodus — {_e(systems)}</title>\n<style>{_CSS}</style>\n</head>\n"
            "<body>\n" + "\n".join(body) + "\n</body>\n</html>\n"
        )
        return [Document(name="report.html", content=page)]

    def _summary(
        self, graph: ArchitectureGraph, risks: list[Risk], plan: MigrationPlan
    ) -> list[str]:
        severities = Counter(r.severity for r in risks)
        fast = Counter(str(c.fast.strategy) for c in plan.containers)
        modern = Counter(str(c.modern.strategy) for c in plan.containers if c.modern)
        t = self._t
        foundation = t(" + fundação", " + foundation") if plan.foundation else ""
        cards = [
            (t("Sistemas", "Systems"), str(len(graph.nodes(NodeKind.SYSTEM)))),
            ("Containers", str(len(graph.nodes(NodeKind.CONTAINER)))),
            (t("Bancos de dados", "Databases"), str(len(graph.nodes(NodeKind.DATA_STORE)))),
            (t("Filas", "Queues"), str(len(graph.nodes(NodeKind.QUEUE)))),
            (
                t("Sistemas externos", "External systems"),
                str(len(graph.nodes(NodeKind.EXTERNAL_SYSTEM))),
            ),
            (
                t("Riscos altos", "High risks"),
                f'<span class="high">{severities[Severity.HIGH]}</span>',
            ),
            (t("Ondas de migração", "Migration waves"), f"{len(plan.waves)}{foundation}"),
        ]
        high, medium = severities[Severity.HIGH], severities[Severity.MEDIUM]
        low = severities[Severity.LOW]
        lines = [
            f"<h2>{t('Resumo', 'Summary')}</h2>",
            '<div class="cards">',
            *[f'<div class="card"><b>{value}</b>{label}</div>' for label, value in cards],
            "</div>",
            "<ul>",
            f"<li><strong>{t('Caminho rápido', 'Fast path')}:</strong> {_counts(fast)}</li>",
            f"<li><strong>{t('Caminho moderno', 'Modern path')}:</strong> "
            f"{_counts(modern) or t('nada a reescrever', 'nothing to rewrite')}</li>",
            t(
                f"<li><strong>Riscos:</strong> {high} altos, {medium} médios, {low} baixos</li>",
                f"<li><strong>Risks:</strong> {high} high, {medium} medium, {low} low</li>",
            ),
        ]
        retire = [c for c in plan.containers if c.retire_candidate]
        if retire:
            names = ", ".join(graph.node(c.container_id).name for c in retire)
            label = t("Candidatos a Retire (confirmar uso)", "Retire candidates (confirm usage)")
            lines.append(f"<li><strong>{label}:</strong> {_e(names)}</li>")
        lines.append("</ul>")
        return [*lines, *self._overview(graph)]

    def _as_is(self, graph: ArchitectureGraph) -> list[str]:
        lines = [
            self._t("<h2>Arquitetura atual (AS-IS)</h2>", "<h2>Current architecture (AS-IS)</h2>"),
            self._t(
                '<p class="muted">Diagrama completo, com os níveis L1/L2/L3, em '
                "<code>as-is/c4.drawio</code>.</p>",
                '<p class="muted">Full diagram, with the L1/L2/L3 levels, in '
                "<code>as-is/c4.drawio</code>.</p>",
            ),
        ]
        if len(graph.nodes(NodeKind.SYSTEM)) > 1:
            context = self._t("Contexto (L1)", "Context (L1)")
            lines.append(self._figure(svg(system_context(graph), C4Svg()), context))
        lines += [self._figure(svg(v, C4Svg()), v.title) for v in container_views(graph)]
        return lines

    def _risks(self, graph: ArchitectureGraph, risks: list[Risk]) -> list[str]:
        """HIGH risks, one row per (risk, detail) with every container it affects."""
        high = [r for r in risks if r.severity is Severity.HIGH]
        others = len(risks) - len(high)
        t = self._t
        lines = [f"<h2>{t('Riscos altos', 'High risks')}</h2>"]
        if not high:
            lines.append(f"<p>{t('Nenhum risco alto detectado.', 'No high risk detected.')}</p>")
        else:
            grouped: dict[tuple[str, str], list[Risk]] = {}
            for r in high:
                grouped.setdefault((r.title, r.detail), []).append(r)
            rows = []
            for (title, detail), group in grouped.items():
                where = sorted(
                    {graph.node(r.container_id).name if r.container_id
                     else t("vários sistemas", "several systems") for r in group}
                )  # fmt: skip
                evidence = [e for r in group for e in r.evidence]
                rows.append(
                    (
                        title,
                        detail,
                        f"{len(where)}: {', '.join(where)}",
                        f"<code>{_e(self._localize(evidence_summary(evidence, 1)))}</code>",
                    )
                )
            headers = [t("Risco", "Risk"), t("Detalhe", "Detail"), t("Onde", "Where"),
                       t("Evidência", "Evidence")]  # fmt: skip
            lines.append(_table(headers, rows, raw_last=True))
        if others:
            lines.append(
                t(
                    f'<p class="muted">Mais {others} risco(s) médio(s)/baixo(s) em '
                    "<code>risks.md</code>.</p>",
                    f'<p class="muted">{others} more medium/low risk(s) in '
                    "<code>risks.md</code>.</p>",
                )
            )
        return lines

    def _migration(self, graph: ArchitectureGraph, plan: MigrationPlan) -> list[str]:
        t = self._t
        paths: dict[tuple[str, str], list[str]] = {}  # the same paths: one row
        for c in plan.containers:
            modern = self._path(c.modern) if c.modern else t("= caminho rápido", "= fast path")
            fast = self._path(c.fast)
            paths.setdefault((fast, modern), []).append(graph.node(c.container_id).name)
        rows = [
            (f"{len(names)}: {', '.join(sorted(names))}", fast, modern)
            for (fast, modern), names in paths.items()
        ]
        lines = [
            f"<h2>{t('Migração', 'Migration')} (7R)</h2>",
            t(
                '<p class="muted">Recomendação por regras, sem IA: caminho rápido '
                "(Rehost/Replatform) para chegar à AWS com o mínimo de mudança e caminho moderno "
                "(Refactor). Detalhes e legenda dos 7R em <code>migration.md</code>.</p>",
                '<p class="muted">Rule-based recommendation, no AI: fast path '
                "(Rehost/Replatform) to reach AWS with the least change and modern path "
                "(Refactor). Details and the 7R legend in <code>migration.md</code>.</p>",
            ),
            _table(
                [
                    "Containers",
                    t("Caminho rápido", "Fast path"),
                    t("Caminho moderno", "Modern path"),
                ],
                rows,
            ),
            f"<h3>{t('Ondas', 'Waves')}</h3>",
        ]
        wave_label = t("Onda", "Wave")
        targets = {i.node_id: i.fast for i in plan.infrastructure}
        if plan.foundation:
            items = ", ".join(f"{graph.node(p).name} → {targets[p]}" for p in plan.foundation)
            foundation = t("Onda 0 — fundação", "Wave 0 — foundation")
            lines.append(f"<p><strong>{foundation}:</strong> {_e(items)}</p>")
        for wave in plan.waves:
            lines.append(f"<p><strong>{wave_label} {wave.number}</strong></p><ul>")
            for group in wave.groups:
                names = ", ".join(graph.node(i).name for i in group.container_ids)
                data = [graph.node(i).name for i in (*group.store_ids, *group.queue_ids)]
                extra = f" + {', '.join(data)}" if data else ""
                why = (
                    f" — {'; '.join(self._localize(r) for r in group.reasons)}"
                    if group.reasons
                    else ""
                )
                lines.append(f"<li><strong>{_e(names)}</strong>{_e(extra)}{_e(why)}</li>")
            lines.append("</ul>")
        return lines

    def _to_be(self, graph: ArchitectureGraph) -> list[str]:
        t = self._t
        platform = t(
            "Segurança · Observabilidade · Plataforma", "Security · Observability · Platform"
        )
        lines = [
            t("<h2>Arquitetura na AWS (TO-BE)</h2>", "<h2>Architecture on AWS (TO-BE)</h2>"),
            t(
                '<p class="muted">Cor da borda = categoria AWS. Diagramas com os ícones oficiais '
                "em <code>to-be/replatform.drawio</code> e <code>to-be/refactor.drawio</code>.</p>",
                '<p class="muted">Border color = AWS category. Diagrams with the official icons '
                "in <code>to-be/replatform.drawio</code> and "
                "<code>to-be/refactor.drawio</code>.</p>",
            ),
            t("<h3>Replatform (caminho rápido)</h3>", "<h3>Replatform (fast path)</h3>"),
        ]
        aws = AwsSvg()
        lines += [self._figure(svg(v, aws, platform), v.title) for v in replatform_views(graph)]
        plan = graph.refactor
        if plan is None:
            return lines
        names = _PRIORITIES if self.language is Language.PT_BR else {}
        priorities = " → ".join(names.get(p, p) for p in self.catalog.priorities)
        lines += [
            t("<h3>Refactor (proposto pela IA)</h3>", "<h3>Refactor (proposed by the AI)</h3>"),
            t(
                f'<p class="muted">Escolhas do catálogo priorizando {priorities}; '
                "justificativas <em>inferidas</em> (revisar antes de aceitar). Decisões "
                "completas em <code>to-be/adr/</code>.</p>",
                f'<p class="muted">Catalog choices prioritizing {priorities}; '
                "<em>inferred</em> rationales (review before accepting). Full decisions in "
                "<code>to-be/adr/</code>.</p>",
            ),
        ]
        lines += [
            self._figure(svg(refactor_view(graph, s), aws, platform), f"Refactor — {s.name}")
            for s in graph.nodes(NodeKind.SYSTEM)
        ]
        chosen: dict[str, list[str]] = {}  # service -> elements: the big picture
        for c in plan.choices:
            chosen.setdefault(c.service, []).append(graph.node(c.node_id).name)
        summary = [
            (service, f"{len(names)}: {', '.join(sorted(names))}")
            for service, names in sorted(chosen.items(), key=lambda item: -len(item[1]))
        ]
        merges = [
            (graph.node(m.source_id).name, graph.node(m.into_id).name, m.justification)
            for m in plan.merges
        ]
        summary += [
            (t("Fundir serviços", "Merge services"), f"{source} {t('em', 'into')} {into}")
            for source, into, _ in merges
        ]
        lines.append(_table([t("Escolha", "Choice"), t("Elementos", "Elements")], summary))
        rows = [
            (t(f"Fundir {source} em {into}", f"Merge {source} into {into}"), "—", why, "")
            for source, into, why in merges
        ]
        default = t(
            "Sem escolha inferida: opção padrão do catálogo",
            "No inferred choice: the catalog's default option",
        )
        rows += [
            (
                graph.node(c.node_id).name,
                c.service,
                c.justification if c.inferred else default,
                f"{c.confidence:.0%}" if c.inferred else t("padrão", "default"),
            )
            for c in plan.choices
        ]
        headers = [t("Elemento", "Element"), t("Escolha", "Choice"),
                   t("Justificativa", "Rationale"), t("Confiança", "Confidence")]  # fmt: skip
        table = _table(headers, rows)
        summary_label = t("Justificativa de cada escolha", "Rationale for each choice")
        lines.append(f"<details><summary>{summary_label} ({len(rows)})</summary>"
                     f"{table}</details>")  # fmt: skip
        return lines

    def _details(self, graph: ArchitectureGraph) -> list[str]:
        t = self._t
        inventory = _markdown_body(_only(InventoryRenderer().render(graph)))
        sections = [(t("Inventário", "Inventory"), inventory)]
        use_cases = _only(UseCasesRenderer().render(graph))
        sections.append(
            (t("Casos de uso (<em>inferidos</em>)", "Use cases (<em>inferred</em>)"),
             _markdown_body(use_cases))
        )  # fmt: skip
        components = [self._figure(svg(v, C4Svg()), v.title) for v in component_views(graph)]
        if components:
            title = t(
                "Componentes (L3) dos containers principais",
                "Components (L3) of the main containers",
            )
            sections.append((title, "\n".join(components)))
        adrs = AdrRenderer(self.catalog).render(graph)
        if adrs:
            adr_html = "\n".join(to_html(d.content, 2) for d in adrs)
            sections.append((t("ADRs do refactor", "Refactor ADRs"), adr_html))
        return [
            f"<h2>{t('Detalhes', 'Details')}</h2>",
            *[
                f"<details><summary>{title}</summary>\n{content}\n</details>"
                for title, content in sections
            ],
        ]

    def _overview(self, graph: ArchitectureGraph) -> list[str]:
        """What each system does (inferred), its containers folded."""
        t = self._t
        lines: list[str] = []
        for system in graph.nodes(NodeKind.SYSTEM):
            containers = [c for c in graph.children(system.id, NodeKind.CONTAINER) if c.description]
            if not system.description and not containers:
                continue
            overview = t("visão geral (<em>inferida</em>)", "overview (<em>inferred</em>)")
            lines.append(f"<h3>{_e(system.name)} — {overview}</h3>")
            if system.description:
                lines.append(f"<p>{self._inferred(system.description.confidence)} "
                             f"{_e(system.description.text)}</p>")  # fmt: skip
            if containers:
                items = "".join(
                    f"<li><strong>{_e(c.name)}:</strong> "
                    f"{self._inferred(c.description.confidence)} {_e(c.description.text)}</li>"
                    for c in containers
                    if c.description
                )
                label = t("O que faz cada container", "What each container does")
                lines.append(f"<details><summary>{label} ({len(containers)})"
                             f"</summary><ul>{items}</ul></details>")  # fmt: skip
        return lines

    def _inferred(self, confidence: float) -> str:
        return f"<em>{self._t('inferido', 'inferred')}</em> ({confidence:.0%}):"

    def _figure(self, diagram: str, caption: str) -> str:
        """A diagram fitted to the page; a click shows it at full size (and back)."""
        zoom = self._t("clique para ampliar", "click to zoom")
        return (
            f"<figure onclick=\"this.classList.toggle('zoom')\"><figcaption>{_e(caption)} "
            f"— {zoom}</figcaption>\n{diagram}\n</figure>"
        )

    def _path(self, path: Path) -> str:
        reason = f" — {self._localize(path.reason)}" if path.reason else ""
        return f"**{path.strategy}** → {path.target}{reason}"


_PRIORITIES = {"cost": "custo", "security": "segurança", "performance": "performance"}


def _only(documents: list[Document]) -> str:
    return documents[0].content if documents else ""


def _markdown_body(markdown: str) -> str:
    """A generated Markdown document without its own title, nested under a report heading."""
    lines = markdown.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
    lines = [line for line in lines if not line.startswith("> ")]  # the document's own notes
    return to_html("\n".join(lines), shift=2)


def _counts(counter: Counter[str]) -> str:
    return ", ".join(f"{count} {name}" for name, count in counter.most_common())


def _table(headers: list[str], rows: Iterable[tuple[str, ...]], raw_last: bool = False) -> str:
    head = "".join(f"<th>{_e(h)}</th>" for h in headers)
    body = []
    for row in rows:
        cells = [inline(cell) for cell in row[:-1]]
        cells.append(row[-1] if raw_last else inline(row[-1]))
        body.append("<tr>" + "".join(f"<td>{cell}</td>" for cell in cells) + "</tr>")
    return f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(body)}</tbody></table>"


def _e(text: str) -> str:
    return html.escape(text, quote=True)
